# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: election.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x65lection.proto\x1a\x1bgoogle/protobuf/empty.proto""\n\x0f\x45lectionRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05"(\n\x13\x43oordinationRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x32\x84\x01\n\x0f\x45lectionService\x12\x33\n\x05\x65lect\x12\x10.ElectionRequest\x1a\x16.google.protobuf.Empty"\x00\x12<\n\ncoordinate\x12\x14.CoordinationRequest\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "election_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _ELECTIONREQUEST._serialized_start = 47
    _ELECTIONREQUEST._serialized_end = 81
    _COORDINATIONREQUEST._serialized_start = 83
    _COORDINATIONREQUEST._serialized_end = 123
    _ELECTIONSERVICE._serialized_start = 126
    _ELECTIONSERVICE._serialized_end = 258
# @@protoc_insertion_point(module_scope)
