# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63lock.proto\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x12\x41\x64justClockRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x01\"\'\n\x12\x46\x65tchClockResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x32\x8b\x01\n\x0c\x43lockService\x12<\n\x0b\x66\x65tch_clock\x12\x16.google.protobuf.Empty\x1a\x13.FetchClockResponse\"\x00\x12=\n\x0c\x61\x64just_clock\x12\x13.AdjustClockRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADJUSTCLOCKREQUEST._serialized_start=44
  _ADJUSTCLOCKREQUEST._serialized_end=80
  _FETCHCLOCKRESPONSE._serialized_start=82
  _FETCHCLOCKRESPONSE._serialized_end=121
  _CLOCKSERVICE._serialized_start=124
  _CLOCKSERVICE._serialized_end=263
# @@protoc_insertion_point(module_scope)
