# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/election.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18src/proto/election.proto\x12\ttictactoe\"\"\n\x0f\x45lectionRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"#\n\x10\x42roadcastRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"$\n\x12\x41\x64justClockRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x01\"\'\n\x12\x46\x65tchClockResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\"\x07\n\x05\x45mpty2\x8b\x01\n\x0f\x45lectionService\x12:\n\x08\x45lection\x12\x1a.tictactoe.ElectionRequest\x1a\x10.tictactoe.Empty\"\x00\x12<\n\tBroadcast\x12\x1b.tictactoe.BroadcastRequest\x1a\x10.tictactoe.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.election_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELECTIONREQUEST._serialized_start=39
  _ELECTIONREQUEST._serialized_end=73
  _BROADCASTREQUEST._serialized_start=75
  _BROADCASTREQUEST._serialized_end=110
  _ADJUSTCLOCKREQUEST._serialized_start=112
  _ADJUSTCLOCKREQUEST._serialized_end=148
  _FETCHCLOCKRESPONSE._serialized_start=150
  _FETCHCLOCKRESPONSE._serialized_end=189
  _EMPTY._serialized_start=191
  _EMPTY._serialized_end=198
  _ELECTIONSERVICE._serialized_start=201
  _ELECTIONSERVICE._serialized_end=340
# @@protoc_insertion_point(module_scope)
