# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x0eSetMarkRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x11\n\tserver_id\x18\x02 \x01(\x05\"3\n\x0fSetMarkResponse\x12\r\n\x05\x62oard\x18\x01 \x01(\t\x12\x11\n\tgame_over\x18\x02 \x01(\x08\" \n\rInformRequest\x12\x0f\n\x07message\x18\x01 \x01(\t2r\n\x0bGameService\x12/\n\x08set_mark\x12\x0f.SetMarkRequest\x1a\x10.SetMarkResponse\"\x00\x12\x32\n\x06inform\x12\x0e.InformRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETMARKREQUEST._serialized_start=43
  _SETMARKREQUEST._serialized_end=96
  _SETMARKRESPONSE._serialized_start=98
  _SETMARKRESPONSE._serialized_end=149
  _INFORMREQUEST._serialized_start=151
  _INFORMREQUEST._serialized_end=183
  _GAMESERVICE._serialized_start=185
  _GAMESERVICE._serialized_end=299
# @@protoc_insertion_point(module_scope)
