# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ngame.proto\x1a\x1bgoogle/protobuf/empty.proto"H\n\x0eSetMarkRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x11\n\tserver_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x01" \n\rInformMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\x95\x02\n\x0bGameService\x12-\n\x08set_mark\x12\x0f.SetMarkRequest\x1a\x0e.InformMessage"\x00\x12\x32\n\x06inform\x12\x0e.InformMessage\x1a\x16.google.protobuf.Empty"\x00\x12\x36\n\nstart_game\x12\x0e.InformMessage\x1a\x16.google.protobuf.Empty"\x00\x12\x34\n\x08\x65nd_game\x12\x0e.InformMessage\x1a\x16.google.protobuf.Empty"\x00\x12\x35\n\tget_board\x12\x16.google.protobuf.Empty\x1a\x0e.InformMessage"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "game_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _SETMARKREQUEST._serialized_start = 43
    _SETMARKREQUEST._serialized_end = 115
    _INFORMMESSAGE._serialized_start = 117
    _INFORMMESSAGE._serialized_end = 149
    _GAMESERVICE._serialized_start = 152
    _GAMESERVICE._serialized_end = 429
# @@protoc_insertion_point(module_scope)
